### ISSUE TITLE
API for å lese fra bildedatabasen

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/artsdatabanken.no#23]
Ønske om å kunne lese ut en oversikt over bilder knyttet til type (naturtype/landskapstype/art..)... og helst også med flagg på det ene bildet som er definert som "dagens" "cover bilde" for typen.

For lastejobber kunne det vært hensiktsmessig om det fantes en indeks-fil (JSON) med alle bilder innenfor ett domene (art, landskap, naturtype) som ble publisert på faste urler.. f.eks. en gang i døgnet.

https://artsdatabanken.no/bilder#_s::1557751232576

**Comment by torstein-a** [comment]
Dette er egnet som en dokumentasjonscase. 
Jeg lager et enkelt API og legger til dokumentasjon på hvordan det blir gjort på intranettet.

**Comment by torstein-a** [comment]
Ligger i prod. Se intranett for detaljer. Cover-flag er ikke satt, trenger litt finpuss der.
