### ISSUE TITLE
På mobil virker ikke menyen. I det heletatt...

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/artsdatabanken.no#25]
Prøvde å navigere meg til kontaktsidene på mobil.
Men, nedfallsmenyen legger seg inne i en bitteliten boks, og til tross for at denne er scrollbar, er ikke lenkene fungerende. Endte med å bruke google i steden.

**Comment by torstein-a** [comment]
Tidligere i vår satte jeg høyde for menyelementet. Jeg må glemt å legge til media-queryen for at det ikke skal være med på små skjermer. I'll fix.

**Comment by torstein-a** [comment]
Oppdatert på prod.
